// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Handler = require("../Handler.js");

function handler(_event, param, callback) {
  return Handler.respondWithObject(callback, {
              Hello: "world!"
            });
}

exports.handler = handler;
/* No side effect */
