// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function respondWithJson(callback, json) {
  return Curry._2(callback, undefined, {
              isBase64Encoded: false,
              statusCode: 200,
              headers: Js_dict.fromList(/* :: */[
                    /* tuple */[
                      "Content-Type",
                      "application/json"
                    ],
                    /* [] */0
                  ]),
              body: JSON.stringify(json)
            });
}

function respondWithObject(callback, obj) {
  return Curry._2(callback, undefined, {
              isBase64Encoded: false,
              statusCode: 200,
              headers: Js_dict.fromList(/* :: */[
                    /* tuple */[
                      "Content-Type",
                      "application/json"
                    ],
                    /* [] */0
                  ]),
              body: JSON.stringify(obj)
            });
}

exports.respondWithJson = respondWithJson;
exports.respondWithObject = respondWithObject;
/* No side effect */
